const MESSAGING = {
  FETCH_REFRESH_DATA: 'FETCH_REFRESH_DATA',
  INVOKE_DATA_COLLECTION: 'INVOKE_DATA_COLLECTION',
  START_DATA_COLLECTION: 'START_DATA_COLLECTION',
  WAIT_FOR_ACTIVE_TAB_LOADS: 'WAIT_FOR_ACTIVE_TAB_LOADS',
  REFRESH_PAGE_DATA: "REFRESH_PAGE_DATA",
  INVOKE_PAGE_REFRESH: "INVOKE_PAGE_REFRESH"
}

const SCRAPING_STATUS = {
  IDLE: 'IDLE',
  COLLECTING: 'COLLECTING',
}


export { MESSAGING, SCRAPING_STATUS }
