const MESSAGING = {
  WAIT_TILL_ACTIVE_TAB_LOADS: 'WAIT_TILL_ACTIVE_TAB_LOADS',
  GET_USAGE_LIMIT: 'GET_USAGE_LIMIT',
  INCREMENT_USAGE: 'INCREMENT_USAGE',
  OPEN_PAYMENT_PAGE: 'OPEN_PAYMENT_PAGE',
}
export const EXTENSION_ID = 'aliexpress-images-downloader-tool'

export { MESSAGING }
