const MESSAGING: Record<string, string> = {
  INVOKE_BATCH_DATA_COLLECTION: 'INVOKE_BATCH_DATA_COLLECTION',
  INVOKE_SINGLE_DATA_COLLECTION: 'INVOKE_SINGLE_DATA_COLLECTION',
  COLLECT_BATCH_PROPERTY_DATA: 'COLLECT_BATCH_PROPERTY_DATA',
  COLLECT_SINGLE_PROPERTY_DATA: 'COLLECT_SINGLE_PROPERTY_DATA',
  CREATE_EXCEL_FILE: 'CREATE_EXCEL_FILE',
  SET_BLOB_FROM_URL: 'SET_BLOB_FROM_URL',
  WAIT_FOR_ACTIVE_TAB_LOADS: 'WAIT_FOR_ACTIVE_TAB_LOADS',
  SAVE_IMAGE: "SAVE_IMAGE",
  CREATE_FOLDER: "CREATE_FOLDER",
  UPDATE_EXCEL_SHEET_DATA: "UPDATE_EXCEL_SHEET_DATA"
}

const INITITAL_DATA = {
  props: [],
  spreadsheetId: ""
}
const SHEET_HEADERS = ["Link", "Title", "Price", "Location", "Sqr", "Pet", "Posted Time", "Description", "Unit details", "Seller Profile", "Images"]
const FB_MARKETPLACE_RENTAL_PAGE = 'https://www.facebook.com/marketplace/category/propertyrentals'

export { MESSAGING, INITITAL_DATA, FB_MARKETPLACE_RENTAL_PAGE, SHEET_HEADERS }
